### ISSUE TITLE
Compiling error on MacOS Sierra

### ISSUE THREAD

**Issue by wenting-zhao** [liffiton/minicard#1]
Hi,

I'm on the newest commit (775d546).  When I tried to compile the binary, I got this error:

```
$ make
Linking: minicard ( minicard/Main.o minicard/Solver.o utils/Options.o utils/System.o )
Undefined symbols for architecture x86_64:
  "Minisat::memUsedPeak()", referenced from:
      printStats(Minisat::Solver&) in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [minicard] Error 1
```

I think this error occurs after the duplicate-literals thing is introduced in the code.  Thanks!

**Comment by wenting-zhao** [comment]
Oh, I even traced back the initial commit (beac636) in the repository and tried to compile the code, and it isn't even working there:

```
$ make
Making dependencies
Compiling: minicard/Main.o
In file included from /Users/zhao/research/solvers/minicard/minicard/Main.cc:36:
In file included from /Users/zhao/research/solvers/minicard/minicard/Dimacs.h:34:
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:58:16: error: friend declaration specifying a default argument must
      be a definition
    friend Lit mkLit(Var var, bool sign = false);
               ^
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:66:14: error: friend declaration specifying a default argument must
      be the only declaration
inline  Lit  mkLit     (Var var, bool sign) { Lit p; p.x = var + var + (int)sign; return p; }
             ^
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:58:16: note: previous declaration is here
    friend Lit mkLit(Var var, bool sign = false);
               ^
2 errors generated.
```

Now I'm not sure where the binary I was using for a long time came from in the first place.  So odd.

**Comment by liffiton** [comment]
I'm not sure the duplicate literal change caused this.  And the initial commit has a known issue with clang.  Can you test a commit before the duplicate literal code was added, say e22687f7?

From what I can see, this compilation error will occur if `__APPLE__` is defined, as `memUsedPeak` was never defined in that case in the original MiniSAT code.  I've tested compiling/running this on OS X before, but perhaps `__APPLE__` wasn't set in those cases and it is for you now for some reason.  It should be an easy fix, but given how the memory tracking/reporting from MiniSAT is flaky anyway, I'm not sure whether to fix it or remove it entirely.

Also, pyMiniSolvers should fail to compile for you as well.  Does it?

**Comment by liffiton** [comment]
Just kidding about pyMiniSolvers; it doesn't use that code, I think.  But I'm still not sure what changed to make you unable to compile minicard.

**Comment by wenting-zhao** [comment]
Here you go (and I tried on almost every single commit, none of them worked):

```
$ git checkout e22687f
Note: checking out 'e22687f'.
HEAD is now at e22687f... Update dates in license file.
$ make
Making dependencies
Compiling: /Users/zhao/research/solvers/minicard/minicard/Main.o
In file included from /Users/zhao/research/solvers/minicard/minicard/Main.cc:36:
In file included from /Users/zhao/research/solvers/minicard/minicard/Dimacs.h:34:
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:58:16: error: friend declaration specifying a default argument must
      be a definition
    friend Lit mkLit(Var var, bool sign = false);
               ^
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:66:14: error: friend declaration specifying a default argument must
      be the only declaration
inline  Lit  mkLit     (Var var, bool sign) { Lit p; p.x = var + var + (int)sign; return p; }
             ^
/Users/zhao/research/solvers/minicard/minicard/SolverTypes.h:58:16: note: previous declaration is here
    friend Lit mkLit(Var var, bool sign = false);
               ^
2 errors generated.
make: *** [/Users/zhao/research/solvers/minicard/minicard/Main.o] Error 1
```

The whole thing is a bit amusing to me.  I did really make an executable binary; otherwise what had I been using?  I think I made the previous binary under /pyminisolvers/minicard, but now I can't even compile over there (I mean, nothing should be changed since I compiled it last time).  I wondered this might be caused by the system update?  Not sure what I can do about it.

**Comment by liffiton** [comment]
Sorry, my mistake.  The next commit (7aa537e23) fixes that friend declaration issues with clang (as the commit message notes).  So anything before that should fail with the friend declaration error.  The memUsedPeak error is something else, and it's possible that your system update changed the compiler to define `__APPLE__` where it hadn't been defined before.

As a simple test, checkout the latest commit and add a new line at line 91 of `utils/System.cc`:

```C++
double Minisat::memUsedPeak(void) { return memUsed(); }
```

That should fix the compilation error, and it's at least no worse than the existing memory usage code for any platform other than linux.

**Comment by wenting-zhao** [comment]
Oh that fixes it!  Open source, hooray!

**Comment by liffiton** [comment]
Okay, I'll just commit that then.  Thanks!
